### ISSUE TITLE
InvalidConfigError: Offset must be a number and can not contain characters

### ISSUE THREAD

**Issue by alexwoolford** [xuren87/node-red-contrib-kafkanode#3]
I tried using v0.2.0 to consume a topic from Kafka and got the following error message:
    `InvalidConfigError: Offset must be a number and can not contain characters`

There were no configs related to offset exposed to the UI, so this is a blocker.

**Comment by Kiir080** [comment]
I have the same issue

**Comment by armiand** [comment]
I have created a fix, see #5
